### ISSUE TITLE
Undying Makes you way too Inmortal

### ISSUE THREAD

**Issue by Laifsyn** [CartoonishVillain/VillanousDifficultyMultipliers#1]
Well, I went testing, and I now can't escape from the void fall without console commands in the server because the death screen closes the chat. So... yeah. It would be nice if there's some "if's" when allowing the player to revive

**Comment by CartoonishVillain** [comment]
Wouldn't call it a bug, it is doing what it's intended to do. **That said** it is a funny oversight I forgot about. Void damage will be the only one I account for

**Comment by Laifsyn** [comment]
So what would happen if someone dies while suffocated by let's say Obsidian? xD

**Comment by CartoonishVillain** [comment]
Well, they got a good 5 minutes of digging obsidian with their hand to do. The likelihood this will ever happen (at least by vanilla standards) is incredibly low. Entire idea of it is that you just can't die if you have it on. Except in a near future patch, to /kill and void damage.

Forgot though on fabric edition it works differently. In that case the player is just done for. Again though, incredibly unlikely

**Comment by CartoonishVillain** [comment]
Patched in 1.1.1 Fabric 1.6.2 Forge
