### ISSUE TITLE
Aging bypassing False value

### ISSUE THREAD

**Issue by Laifsyn** [CartoonishVillain/VillanousDifficultyMultipliers#2]
Hi, it's me again. So the Aging multiplier is still working even though One has it disabled. For tests sakes, using Carpet's tick warp helps to have it done in minutes, or you might set the aging limit to 1 too though.

I've just set my age value to 1 in a world where I was testing without the mod installed before. Once I bred the horses, they just instant disappear.

So far(I haven't tested with other animals) horses can disappear regardless of VDM Aging active state

**Comment by Laifsyn** [comment]
Mod list
![image](https://user-images.githubusercontent.com/99366187/155427629-711f6815-7e90-48f8-bf37-51b7e70521d5.png)

**Comment by CartoonishVillain** [comment]
Apologies for the delay, will look into this today. Thank you for providing the mod list, though in the future do try to post your game version, loader (and loader version) and mod version with your initial issue. That said, with your modlist here I can gather this information well enough.

**Comment by CartoonishVillain** [comment]
Resolved in [this commit](https://github.com/CartoonishVillain/VillainousDifficultyMultipliers-Fabric/commit/5e6efe810a2197b0f9d61211bbcc5c68bb3bab36)

version 1.1.2 (when available)
